spring:
  datasource:
    url: jdbc:mysql://39.105.38.90:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    primary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yizhu.entity
  configuration:
  map-underscore-to-camel-case: true