spring:
  datasource:
    url: jdbc:mysql://rm-uf6v4buw00300dm876o.mysql.rds.aliyuncs.com:3306/user_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: Zhao1992
    driver-class-name: com.mysql.jdbc.Driver
    primary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml